export const STORAGE_KEYS = {
  productiveHosts: "productiveHosts",
  distractionHosts: "distractionHosts",
  dailyBuckets: "dailyBuckets",
  dailyByHost: "dailyByHost",
  sessions: "sessions",
  activeSessionId: "activeSessionId",
  pauseUntil: "pauseUntil",
  onboardingDone: "onboardingDone",
  dailyGoalMinutes: "dailyGoalMinutes",
  weeklyGoalMinutes: "weeklyGoalMinutes",
  pomodoroNotify: "pomodoroNotify",
  pomodoroState: "pomodoroState",
  focusModeEnabled: "focusModeEnabled",
  focusModeBlockedSites: "focusModeBlockedSites",
  focusModeOverrideCooldownMs: "focusModeOverrideCooldownMs",
  focusModeLastOverrideTime: "focusModeLastOverrideTime",
  focusModeOverrideDuration: "focusModeOverrideDuration",
  lockedTabIds: "lockedTabIds",
  deepFocusEnabled: "deepFocusEnabled",
} as const;
